DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,

  UNIQUE(email),

  CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  requester_id BIGINT NOT NULL,

  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT requester_fk FOREIGN KEY (requester_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  request_id BIGINT NOT NULL,

  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT owner_fk
          foreign key (owner_id) references users,
  CONSTRAINT request_fk
          foreign key (request_id) references requests
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  status VARCHAR(255) NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,

  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT booker_fk
          foreign key (booker_id) references users,
  CONSTRAINT item_fk
           foreign key (item_id) references items
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(512) NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  create_date TIMESTAMP NOT NULL,

  CONSTRAINT pk_comment PRIMARY KEY (id),
  CONSTRAINT comment_item_fk
          foreign key (item_id) references items,
  CONSTRAINT author_fk
          foreign key (author_id) references users
);